"""add_session_status

Revision ID: 9823bb193ec6
Revises: 22b862459bbc
Create Date: 2026-02-01 17:07:25.140854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9823bb193ec6'
down_revision: Union[str, Sequence[str], None] = '22b862459bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('bookmark_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['verse_id'], ['quran_verses.verse_id'], ),
    sa.PrimaryKeyConstraint('bookmark_id')
    )
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.drop_index(op.f('ix_quran_translations_translator_name'), table_name='quran_translations')
    op.drop_index(op.f('ix_quran_verses_lookup'), table_name='quran_verses')
    op.drop_index(op.f('ix_quran_verses_surah_number'), table_name='quran_verses')
    op.add_column('reading_sessions', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('reading_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reading_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('verse_read_history', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('verse_read_history', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('verse_read_history', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verse_read_history', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('verse_read_history', 'updated_at')
    op.drop_column('verse_read_history', 'created_at')
    op.drop_column('reading_sessions', 'updated_at')
    op.drop_column('reading_sessions', 'created_at')
    op.drop_column('reading_sessions', 'status')
    op.create_index(op.f('ix_quran_verses_surah_number'), 'quran_verses', ['surah_number'], unique=False)
    op.create_index(op.f('ix_quran_verses_lookup'), 'quran_verses', ['surah_number', 'verse_number'], unique=True)
    op.create_index(op.f('ix_quran_translations_translator_name'), 'quran_translations', ['translator_name'], unique=False)
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
